import 'package:flutter/material.dart';
import 'package:lucide_icons_flutter/lucide_icons.dart';

final Map<String, IconData> featherIconsMap = {
  'activity': LucideIcons.activity,
  'airplay': LucideIcons.airplay,
  'alertCircle': LucideIcons.alertCircle,
  'aperture': LucideIcons.aperture,
  'archive': LucideIcons.archive,
  'arrowUpCircle': LucideIcons.arrowUpCircle,
  'arrowRightCircle': LucideIcons.arrowRightCircle,
  'arrowDownCircle': LucideIcons.arrowDownCircle,
  'arrowLeftCircle': LucideIcons.arrowLeftCircle,
  'award': LucideIcons.award,
  'barChart': LucideIcons.barChart,
  'barChart2': LucideIcons.barChart2,
  'battery': LucideIcons.battery,
  'batteryCharging': LucideIcons.batteryCharging,
  'bell': LucideIcons.bell,
  'bluetooth': LucideIcons.bluetooth,
  'book': LucideIcons.book,
  'bookmark': LucideIcons.bookmark,
  'box': LucideIcons.box,
  'briefcase': LucideIcons.briefcase,
  'calendar': LucideIcons.calendar,
  'camera': LucideIcons.camera,
  'cast': LucideIcons.cast,
  'checkCircle': LucideIcons.checkCircle,
  'chevronRight': LucideIcons.chevronRight,
  'clipboard': LucideIcons.clipboard,
  'clock': LucideIcons.clock,
  'cloud': LucideIcons.cloud,
  'code': LucideIcons.code,
  'command': LucideIcons.command,
  'compass': LucideIcons.compass,
  'cpu': LucideIcons.cpu,
  'crosshair': LucideIcons.crosshair,
  'database': LucideIcons.database,
  'edit': LucideIcons.edit,
  'feather': LucideIcons.feather,
  'file': LucideIcons.file,
  'fileText': LucideIcons.fileText,
  'film': LucideIcons.film,
  'folder': LucideIcons.folder,
  'globe': LucideIcons.globe,
  'grid': LucideIcons.grid,
  'hammer': LucideIcons.hammer,
  'hardDrive': LucideIcons.hardDrive,
  'hash': LucideIcons.hash,
  'headphones': LucideIcons.headphones,
  'heart': LucideIcons.heart,
  'helpCircle': LucideIcons.helpCircle,
  'hexagon': LucideIcons.hexagon,
  'home': LucideIcons.home,
  'image': LucideIcons.image,
  'inbox': LucideIcons.inbox,
  'info': LucideIcons.info,
  'key': LucideIcons.key,
  'layers': LucideIcons.layers,
  'layout': LucideIcons.layout,
  'lifeBuoy': LucideIcons.lifeBuoy,
  'link': LucideIcons.link,
  'list': LucideIcons.list,
  'lock': LucideIcons.lock,
  'map': LucideIcons.map,
  'maximize': LucideIcons.maximize,
  'messageCircle': LucideIcons.messageCircle,
  'messageSquare': LucideIcons.messageSquare,
  'mic': LucideIcons.mic,
  'monitor': LucideIcons.monitor,
  'moon': LucideIcons.moon,
  'music': LucideIcons.music,
  'navigation': LucideIcons.navigation,
  'package': LucideIcons.package,
  'paperclip': LucideIcons.paperclip,
  'penTool': LucideIcons.penTool,
  'pieChart': LucideIcons.pieChart,
  'play': LucideIcons.play,
  'playCircle': LucideIcons.playCircle,
  'power': LucideIcons.power,
  'printer': LucideIcons.printer,
  'radio': LucideIcons.radio,
  'refreshCw': LucideIcons.refreshCw,
  'save': LucideIcons.save,
  'scissors': LucideIcons.scissors,
  'search': LucideIcons.search,
  'send': LucideIcons.send,
  'server': LucideIcons.server,
  'settings': LucideIcons.settings,
  'shield': LucideIcons.shield,
  'shoppingBag': LucideIcons.shoppingBag,
  'shoppingCart': LucideIcons.shoppingCart,
  'shuffle': LucideIcons.shuffle,
  'skipBack': LucideIcons.skipBack,
  'skipForward': LucideIcons.skipForward,
  'sliders': LucideIcons.sliders,
  'smartphone': LucideIcons.smartphone,
  'speaker': LucideIcons.speaker,
  'star': LucideIcons.star,
  'sun': LucideIcons.sun,
  'target': LucideIcons.target,
  'terminal': LucideIcons.terminal,
  'trash': LucideIcons.trash,
  'trash2': LucideIcons.trash2,
  'tv': LucideIcons.tv,
  'type': LucideIcons.type,
  'umbrella': LucideIcons.umbrella,
  'unlock': LucideIcons.unlock,
  'upload': LucideIcons.upload,
  'user': LucideIcons.user,
  'video': LucideIcons.video,
  'volume': LucideIcons.volume,
  'volume2': LucideIcons.volume2,
  'watch': LucideIcons.watch,
  'wifi': LucideIcons.wifi,
  'zap': LucideIcons.zap,
};

// Legacy `icon` values that predate the current set. Macros saved with one still render,
// but they are not offered in the picker -- each points at the glyph that replaced it.
const Map<String, String> legacyIconAliases = {
  'text': 'type',
};

/// The glyph for an `icon` name, following [legacyIconAliases]; null if the name is unknown.
///
/// Every place that turns a name into a glyph goes through here. Three of them used to
/// special-case 'hammer', 'text' and 'mic' inline with Material icons, which drifted: the
/// editor preview drew Icons.build for 'hammer' while the save path, which rasterises only
/// names present in [featherIconsMap], sent no bitmap at all. Picking those two produced a
/// macro that looked fine in the app and had a blank face on the device.
IconData? resolveIcon(String? name) {
  if (name == null) return null;
  return featherIconsMap[name] ?? featherIconsMap[legacyIconAliases[name]];
}
