#!/usr/bin/env python3
"""Generate the firmware's Lucide glyph set from the companion app's icon map.

The app's macroIcons map is the single source of truth for which icons exist (see
docs/superpowers/specs/2026-09-23-waveshare-icon-rendering-design.md 3.2). This script derives
the firmware's font and name table from it, so the two can only drift by someone failing to
re-run this -- which shows up as icons degrading to the app-supplied bitmap, never as a mismatch
that renders the wrong glyph.

Usage:  python design/generate_icon_font.py
"""
import hashlib
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MACRO_ICONS = REPO / "companion_app/lib/utils/macro_icons.dart"
FONT_TTF = REPO / "tools/fonts/Lucide.ttf"
OUT_FONT = REPO / "firmware/Waveshare_LVGL_Test/lucide_48.c"
OUT_NAMES = REPO / "firmware/Waveshare_LVGL_Test/icon_names.h"
FONT_PX = 48

# The installed package. Pinned by companion_app/pubspec.lock; update here if that version moves.
LUCIDE_PKG = Path.home() / (
    "AppData/Local/Pub/Cache/hosted/pub.dev/lucide_icons_flutter-3.1.15/lib/lucide_icons.dart"
)

# "'play': LucideIcons.play," -- the app map's entry shape.
MAP_ENTRY = re.compile(r"^\s*'([A-Za-z0-9_]+)':\s*LucideIcons\.([A-Za-z0-9_]+)\s*,", re.M)
# "static const IconData play = const IconData(57660," -- the package's declaration shape.
DECL = re.compile(
    r"static const IconData\s+([A-Za-z0-9_]+)\s*=\s*const IconData\(\s*(\d+)\s*,", re.M
)


def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def main():
    if not MACRO_ICONS.exists():
        die(f"cannot find {MACRO_ICONS}")
    if not FONT_TTF.exists():
        die(f"cannot find {FONT_TTF} -- see this script's task in the M12 plan, step 2")
    if not LUCIDE_PKG.exists():
        die(f"cannot find the lucide package at {LUCIDE_PKG}; run `flutter pub get` first")

    entries = MAP_ENTRY.findall(MACRO_ICONS.read_text(encoding="utf-8"))
    if not entries:
        die("parsed zero icons out of macro_icons.dart -- has the map's format changed?")

    codepoints = {m[0]: int(m[1]) for m in DECL.findall(LUCIDE_PKG.read_text(encoding="utf-8"))}

    resolved = {}
    missing = []
    for name, ident in entries:
        cp = codepoints.get(ident)
        if cp is None:
            missing.append(f"{name} -> LucideIcons.{ident}")
        else:
            resolved[name] = cp
    if missing:
        die("these map entries have no codepoint in the installed package:\n  "
            + "\n  ".join(missing))

    # Sorted by byte order, because the firmware binary-searches with strcmp().
    ordered = sorted(resolved.items(), key=lambda kv: kv[0].encode("utf-8"))

    # Version = a hash of exactly what the device can draw, so it changes if and only if the
    # set does. The app uses it to know whether its cached glyph list is still valid.
    digest = hashlib.sha256(
        "".join(f"{n}:{c};" for n, c in ordered).encode("utf-8")
    ).hexdigest()[:12]

    write_names_header(ordered, digest)
    run_font_conv([c for _, c in ordered])

    print(f"generated {len(ordered)} glyphs, set version {digest}")
    print(f"  {OUT_NAMES}")
    print(f"  {OUT_FONT}")


def write_names_header(ordered, digest):
    lines = [
        "// GENERATED by design/generate_icon_font.py -- DO NOT EDIT.",
        "//",
        "// Derived from companion_app/lib/utils/macro_icons.dart, which is the single source of",
        "// truth for icon names. Re-run the generator after changing that map; a name present in",
        "// the app but missing here degrades to the app-supplied icon_bmp48, which is correct but",
        "// silent, so the regeneration step is easy to forget and worth checking in review.",
        "//",
        "// Sorted by strcmp order: icon_codepoint() binary-searches this table.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "  const char *name;",
        "  uint32_t    cp;",
        "} icon_name_entry_t;",
        "",
        f'#define ICON_SET_VERSION "{digest}"',
        f"#define ICON_NAMES_COUNT {len(ordered)}",
        "",
        "static const icon_name_entry_t ICON_NAMES[ICON_NAMES_COUNT] = {",
    ]
    width = max(len(n) for n, _ in ordered) + 3
    for name, cp in ordered:
        lines.append(f'  {{ {(chr(34) + name + chr(34)):<{width}} 0x{cp:04X} }},')
    lines += ["};", ""]
    OUT_NAMES.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def run_font_conv(codepoints):
    # Flags match the convention recorded in orbitron_18.c's generated header. --no-compress is
    # mandatory: lv_conf.h sets LV_USE_FONT_COMPRESSED 0, and a compressed font against that
    # config renders garbage rather than failing to build.
    ranges = ",".join(f"0x{c:04X}" for c in codepoints)
    # On Windows, npm installs a .cmd shim; subprocess's list form doesn't apply PATHEXT
    # resolution the way a shell does, so a bare "lv_font_conv" raises FileNotFoundError even
    # though it's on PATH. shutil.which() does the same PATHEXT search a shell would.
    exe = shutil.which("lv_font_conv") or "lv_font_conv"
    cmd = [
        exe,
        "--font", str(FONT_TTF),
        "--size", str(FONT_PX),
        "--bpp", "4",
        "--format", "lvgl",
        "--range", ranges,
        "--no-compress",
        "--lv-include", "lvgl.h",
        "-o", str(OUT_FONT),
    ]
    try:
        subprocess.run(cmd, check=True)
    except FileNotFoundError:
        die("lv_font_conv not found. Install it: npm install -g lv_font_conv")
    except subprocess.CalledProcessError as e:
        die(f"lv_font_conv failed with exit {e.returncode}")


if __name__ == "__main__":
    main()
