import os
import urllib.request
import urllib.error
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPM
from PIL import Image

ICONS_TO_FETCH = ["tool", "type", "mic"]
OUTPUT_HEADER = "firmware/M5_M6_config/icons.h"
BASE_URL = "https://raw.githubusercontent.com/feathericons/feather/master/icons/"

def fetch_and_convert(icon_name):
    url = f"{BASE_URL}{icon_name}.svg"
    svg_path = f"{icon_name}.svg"
    png_path = f"{icon_name}.png"
    
    print(f"Fetching {icon_name}.svg...")
    try:
        req = urllib.request.urlopen(url)
        svg_data = req.read().decode('utf-8')
        svg_data = svg_data.replace('currentColor', 'black')
        with open(svg_path, 'w') as f:
            f.write(svg_data)
    except Exception as e:
        print(f"Failed to fetch {icon_name}: {e}")
        return None

    # Convert SVG to PNG using svglib and reportlab
    # Feather icons are usually 24x24, we'll scale them to 24x24 for XBM
    print(f"Rendering {icon_name}...")
    drawing = svg2rlg(svg_path)
    # The SVG drawing is usually 24x24, but let's make sure it's rasterized cleanly
    # renderPM supports a DPI parameter. Default is 72.
    renderPM.drawToFile(drawing, png_path, fmt="PNG", dpi=72)
    
    # Open with PIL to convert to 1-bit XBM format
    img = Image.open(png_path)
    
    # Convert to grayscale then to 1-bit pixels (threshold)
    img = img.convert("L")
    
    # We want white drawing on black background (or vice versa).
    # Feather icons are black lines on transparent background.
    # We'll map the black lines to '1' in XBM (which draws with the chosen color).
    
    # XBM format requires width to be a multiple of 8 if we are generating raw bytes,
    # but XBM itself pads rows to bytes.
    width, height = img.size
    
    bytes_per_row = (width + 7) // 8
    xbm_data = []
    
    for y in range(height):
        for x_byte in range(bytes_per_row):
            byte = 0
            for bit in range(8):
                x = x_byte * 8 + bit
                if x < width:
                    # pixel is 0-255. Background is white (255), lines are black (0).
                    # But svglib might have drawn it differently if transparent?
                    # Since SVG was black stroke, rendering it usually makes lines black.
                    # Let's check pixel value
                    p = img.getpixel((x, y))
                    if p < 128: # Dark pixel = line
                        byte |= (1 << bit)
            xbm_data.append(byte)
            
    # Cleanup temp files
    os.remove(svg_path)
    os.remove(png_path)
            
    return width, height, xbm_data

def generate_header():
    print("Generating icons.h...")
    header_content = "// Auto-generated by scripts/generate_icons.py\n"
    header_content += "#pragma once\n\n"
    
    for icon in ICONS_TO_FETCH:
        result = fetch_and_convert(icon)
        if result:
            width, height, data = result
            header_content += f"const int icon_{icon}_width = {width};\n"
            header_content += f"const int icon_{icon}_height = {height};\n"
            header_content += f"const uint8_t icon_{icon}_bits[] PROGMEM = {{\n  "
            
            # Format bytes as hex
            hex_bytes = [f"0x{b:02x}" for b in data]
            # Wrap to 12 bytes per line
            for i in range(0, len(hex_bytes), 12):
                header_content += ", ".join(hex_bytes[i:i+12])
                if i + 12 < len(hex_bytes):
                    header_content += ",\n  "
            header_content += "\n};\n\n"
            
    # Make sure output directory exists
    os.makedirs(os.path.dirname(OUTPUT_HEADER), exist_ok=True)
    with open(OUTPUT_HEADER, "w") as f:
        f.write(header_content)
    print(f"Successfully wrote {OUTPUT_HEADER}")

if __name__ == "__main__":
    generate_header()
