#!/usr/bin/env python3
"""Sign a firmware image for OTA, and emit the manifest the app ships.

The private key comes from DRAUPNIR_OTA_KEY and nowhere else -- no default path, no search. See
tools/ota_keys/README.md for why.

Usage:
  DRAUPNIR_OTA_KEY=... python tools/sign_firmware.py --image <path> --version 1.0.1
  DRAUPNIR_OTA_KEY=... python tools/sign_firmware.py --emit-pubkey
"""
import argparse
import hashlib
import json
import os
import sys
from pathlib import Path

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, utils

REPO = Path(__file__).resolve().parent.parent
PUBKEY_H = REPO / "firmware/Waveshare_LVGL_Test/ota_pubkey.h"
MANIFEST = REPO / "companion_app/assets/firmware/manifest.json"


def die(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def load_key():
    path = os.environ.get("DRAUPNIR_OTA_KEY")
    if not path:
        die("DRAUPNIR_OTA_KEY is not set. This script will not guess at a key path -- see "
            "tools/ota_keys/README.md.")
    if not Path(path).exists():
        die(f"DRAUPNIR_OTA_KEY points at {path}, which does not exist.")
    key = serialization.load_pem_private_key(Path(path).read_bytes(), password=None)
    if not isinstance(key, ec.EllipticCurvePrivateKey):
        die("key is not an EC private key; expected ECDSA P-256")
    if key.curve.name != "secp256r1":
        die(f"key curve is {key.curve.name}; the firmware only verifies secp256r1 (P-256)")
    return key


def emit_pubkey(key):
    der = key.public_key().public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    rows = []
    for i in range(0, len(der), 12):
        rows.append("  " + " ".join(f"0x{b:02X}," for b in der[i:i + 12]))
    body = "\n".join(rows)
    PUBKEY_H.write_text(
        "// GENERATED by tools/sign_firmware.py --emit-pubkey -- DO NOT EDIT.\n"
        "//\n"
        "// ECDSA P-256 public key, DER SubjectPublicKeyInfo. The device verifies every OTA image\n"
        "// against this. Replacing it invalidates every image signed with the old key, so a key\n"
        "// rotation must ship as an update signed with the OLD key -- there is no other path.\n"
        "#pragma once\n\n"
        "#include <stdint.h>\n\n"
        f"static const uint8_t OTA_PUBKEY_DER[] = {{\n{body}\n}};\n\n"
        "#define OTA_PUBKEY_DER_LEN (sizeof(OTA_PUBKEY_DER))\n",
        encoding="utf-8", newline="\n")
    print(f"wrote {PUBKEY_H} ({len(der)} bytes)")


def sign_image(key, image_path, version):
    data = Path(image_path).read_bytes()
    if not data:
        die(f"{image_path} is empty")
    digest = hashlib.sha256(data).digest()
    sig = key.sign(digest, ec.ECDSA(utils.Prehashed(hashes.SHA256())))

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    out = Path(MANIFEST.parent / "firmware.bin")
    out.write_bytes(data)
    MANIFEST.write_text(json.dumps({
        "version": version,
        "size": len(data),
        "sha256": digest.hex(),
        "sig": sig.hex(),
    }, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"signed {len(data)} bytes, version {version}")
    print(f"  sha256 {digest.hex()}")
    print(f"  {out}")
    print(f"  {MANIFEST}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--image")
    ap.add_argument("--version")
    ap.add_argument("--emit-pubkey", action="store_true")
    args = ap.parse_args()

    key = load_key()
    if args.emit_pubkey:
        emit_pubkey(key)
        return
    if not args.image or not args.version:
        die("--image and --version are required unless --emit-pubkey is given")
    sign_image(key, args.image, args.version)


if __name__ == "__main__":
    main()
